site_name: dj-tracker
site_url: https://tijani-dia.github.io/dj-tracker/
repo_url: https://github.com/tijani-dia/dj-tracker
repo_name: tijani-dia/dj-tracker
theme:
  name: material
extra:
  analytics:
    provider: google
    property: G-68QPWVSX21

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial:
      - Set up project: tutorial/setup.md
      - Detect and resolve related queries: tutorial/detect_and_resolve_related_queries.md
      - Use only/defer: tutorial/use_only_or_defer.md
      - Use values/values_list: tutorial/use_values_or_values_list.md
      - Use iterator: tutorial/use_iterator.md
      - Final notes: tutorial/final_notes.md
  - Dashboard: dashboard.md
  - Configuration: configuration.md
